openapi: 3.0.0
info:
  title: Packet API
  version: 1.0.0

servers:
  - url: http://localhost:8000

paths:
  /packets:
    get:
      summary: Get list of packets
      operationId: getPackets
      security:
        - BearerAuth: []
      # Filters beased on datetime_ and station_id
      parameters:
        - name: datetime_
          in: query
          required: false
          schema:
            type: string
            format: date-time
        - name: station_id
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: List of packets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Packet'
        '401':
          description: Unauthorized

        default:
          description: "Unexpected error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /packets/{packet_id}:
    put:
      summary: Update a specific packet
      operationId: updatePacket
      security:
        - BearerAuth: []
      parameters:
        - name: packet_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Packet'
      responses:
        '200':
          description: Packet updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Packet'
        '404':
          description: Packet not found
        '401':
          description: Unauthorized

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Packet:
      type: object
      required:
        - id
        - datetime_
        - station_id
        - temperature_celsius
        - moisture_perc
        - wind_speed_kmh
        - wind_direction
        - rain_meas_mm
      properties:
        id:
          type: integer
        datetime_:
          type: string
          format: date-time
        station_id:
          type: integer
        temperature_celsius:
          type: number  
          format: float
        moisture_perc:
          type: number  
          format: float
        wind_speed_kmh:
          type: number
          format: float
        wind_direction:
          type: string
          enum:
            - south
            - north
            - west
            - east
        rain_meas_mm:
          type: number
          format: float

    ErrorResponse:
        type: object
        required:
          - message
        properties:
         message:
           type: string