openapi: 3.0.0
info:
  title: Packet API
  version: 1.0.0

paths:
  /packets:
    get:
      summary: Get list of packets
      operationId: getPackets
      responses:
        '200':
          description: List of packets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Packet'
        default:
          description: "Unexpected error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    Packet:
      type: object
      required:
        - timestamp
        - station_id
        - temperature_celsium
        - moisture_perc
        - wind_speed_kmh
        - wind_direction
        - rain_meas_mm
      properties:
        timestamp:
          type: string
        station_id:
          type: integer
        temperature_celsium:
          type: number  
          format: float
        moisture_perc:
          type: number  
          format: float
        wind_speed_kmh:
          type: number
          format: float
        wind_direction:
          type: string
          enum:
            - south
            - north
            - west
            - east
        rain_meas_mm:
          type: number
          format: float

    ErrorResponse:
        type: object
        required:
          - message
        properties:
         message:
           type: string